"""Add offboarding workflow and AI fields

Revision ID: 15e70bffbaa3
Revises: d5cc8e7fa36a
Create Date: 2026-06-19 08:26:29.565664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e70bffbaa3'
down_revision: Union[str, Sequence[str], None] = 'd5cc8e7fa36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offboarding_records', sa.Column('actual_exit_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offboarding_records', sa.Column('exit_interview_notes', sa.Text(), nullable=True))
    op.add_column('offboarding_records', sa.Column('ai_sentiment', sa.String(), nullable=True))
    op.add_column('offboarding_records', sa.Column('ai_primary_reason', sa.String(), nullable=True))
    op.add_column('offboarding_records', sa.Column('ai_secondary_reason', sa.String(), nullable=True))
    op.add_column('offboarding_records', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('offboarding_records', sa.Column('ai_risk_level', sa.String(), nullable=True))
    op.add_column('offboarding_records', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offboarding_records', 'analyzed_at')
    op.drop_column('offboarding_records', 'ai_risk_level')
    op.drop_column('offboarding_records', 'ai_summary')
    op.drop_column('offboarding_records', 'ai_secondary_reason')
    op.drop_column('offboarding_records', 'ai_primary_reason')
    op.drop_column('offboarding_records', 'ai_sentiment')
    op.drop_column('offboarding_records', 'exit_interview_notes')
    op.drop_column('offboarding_records', 'actual_exit_date')
    # ### end Alembic commands ###
