"""add leavestable

Revision ID: 5d179f113962
Revises: ed0ad19e7233
Create Date: 2026-02-28 20:53:58.869147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d179f113962'
down_revision: Union[str, Sequence[str], None] = 'ed0ad19e7233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- autogenerated table creation will be here, don't touch it ---

    # Seed default leave policies
    op.execute("""
        INSERT INTO leave_policies (role_name, leave_type, default_days) VALUES
        ('faculty',          'casual', 12),
        ('faculty',          'sick',   10),
        ('faculty',          'earned', 30),
        ('accountant',       'casual', 10),
        ('accountant',       'sick',   10),
        ('accountant',       'earned', 20),
        ('employee',         'casual', 10),
        ('employee',         'sick',   10),
        ('employee',         'earned', 20),
        ('department_head',  'casual', 12),
        ('department_head',  'sick',   10),
        ('department_head',  'earned', 30)
        ON CONFLICT DO NOTHING;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

