"""BCNF Normalization

Revision ID: 8c570c54459a
Revises: 999999999999
Create Date: 2026-06-10 10:46:59.358735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c570c54459a'
down_revision: Union[str, Sequence[str], None] = '999999999999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_branches',
    sa.Column('ifsc_code', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ifsc_code')
    )
    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('default_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', 'leave_type', name='uq_policy_role_leavetype')
    )
    op.create_table('postal_codes',
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pincode')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_addresses',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pincode'], ['postal_codes.pincode'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_emergency_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_financials',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('uan_number', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('ifsc_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ifsc_code'], ['bank_branches.ifsc_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('pending_confirmation', sa.Text(), nullable=True),
    sa.Column('llm_used', sa.String(length=30), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_employments',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('staff_category', sa.String(), nullable=True),
    sa.Column('employment_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='EmploymentType', create_type=False), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('join_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reporting_manager_id', sa.String(), nullable=True),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_constraint(op.f('announcement_reads_announcement_id_user_id_key'), 'announcement_reads', type_='unique')
    op.drop_constraint(op.f('announcement_reads_announcement_id_fkey'), 'announcement_reads', type_='foreignkey')
    op.create_foreign_key(None, 'announcement_reads', 'announcements', ['announcement_id'], ['id'])
    op.alter_column('announcements', 'priority',
               existing_type=postgresql.ENUM('NORMAL', 'IMPORTANT', 'URGENT', name='AnnouncementPriority'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('appraisal_cycles', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'CLOSED', name='CycleStatus'),
               type_=sa.String(),
               nullable=False)
    op.drop_column('appraisal_cycles', 'created_at')
    op.drop_column('appraisal_cycles', 'updated_at')
    op.alter_column('attendance', 'status',
               existing_type=postgresql.ENUM('PRESENT', 'ABSENT', 'HALF_DAY', 'HOLIDAY', 'WEEKEND', 'ON_LEAVE', name='AttendanceStatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('attendance_employee_id_date_key'), 'attendance', type_='unique')
    op.create_unique_constraint('uq_attendance_employee_date', 'attendance', ['employee_id', 'date'])
    op.create_foreign_key(None, 'attendance', 'users', ['corrected_by'], ['id'])
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'details')
    op.create_foreign_key(None, 'departments', 'users', ['director_id'], ['id'])
    op.alter_column('holidays', 'type',
               existing_type=postgresql.ENUM('NATIONAL', 'REGIONAL', 'UNIVERSITY', name='HolidayType'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_PENDING', 'ATTENDANCE_FLAGGED', 'ANNOUNCEMENT', 'ONBOARDING', 'PAYSLIP', 'SYSTEM', name='NotificationType'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('offboarding_records', 'status',
               existing_type=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='OffboardingStatus'),
               type_=sa.String(),
               nullable=False)
    op.drop_column('offboarding_records', 'personal_email')
    op.drop_column('offboarding_records', 'created_at')
    op.drop_column('offboarding_records', 'notes')
    op.drop_column('offboarding_records', 'forwarding_address')
    op.drop_column('offboarding_records', 'resignation_date')
    op.drop_column('offboarding_records', 'updated_at')
    op.add_column('offboarding_tasks', sa.Column('offboarding_record_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('offboarding_tasks_offboarding_id_fkey'), 'offboarding_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'offboarding_tasks', 'offboarding_records', ['offboarding_record_id'], ['id'])
    op.drop_column('offboarding_tasks', 'status')
    op.drop_column('offboarding_tasks', 'created_at')
    op.drop_column('offboarding_tasks', 'offboarding_id')
    op.drop_column('offboarding_tasks', 'notes')
    op.alter_column('onboarding_employees', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='OnboardingStatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('onboarding_tasks', sa.Column('onboarding_record_id', sa.String(), nullable=True))
    op.add_column('onboarding_tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('onboarding_tasks_onboarding_id_fkey'), 'onboarding_tasks', type_='foreignkey')
    op.drop_constraint(op.f('onboarding_tasks_assigned_to_id_fkey'), 'onboarding_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_tasks', 'onboarding_employees', ['onboarding_record_id'], ['id'])
    op.drop_column('onboarding_tasks', 'created_at')
    op.drop_column('onboarding_tasks', 'order')
    op.drop_column('onboarding_tasks', 'status')
    op.drop_column('onboarding_tasks', 'due_date')
    op.drop_column('onboarding_tasks', 'assigned_to_id')
    op.drop_column('onboarding_tasks', 'priority')
    op.drop_column('onboarding_tasks', 'updated_at')
    op.drop_column('onboarding_tasks', 'onboarding_id')
    op.alter_column('performance_goals', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'DIRECTOR_REVIEWED', 'FINALIZED', name='GoalStatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('performance_goals_employee_id_cycle_id_key'), 'performance_goals', type_='unique')
    op.create_unique_constraint('uq_goal_employee_cycle', 'performance_goals', ['employee_id', 'cycle_id'])
    op.alter_column('recruitment_applicants', 'status',
               existing_type=postgresql.ENUM('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFERED', 'HIRED', 'REJECTED', name='ApplicantStatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('recruitment_applicants_job_id_fkey'), 'recruitment_applicants', type_='foreignkey')
    op.create_foreign_key(None, 'recruitment_applicants', 'recruitment_jobs', ['job_id'], ['id'])
    op.alter_column('recruitment_jobs', 'type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='EmploymentType'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('recruitment_jobs', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'PAUSED', 'FILLED', name='RecruitmentStatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('system_settings', 'working_days',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('users_position_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_reporting_manager_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'street')
    op.drop_column('users', 'emergency_relation')
    op.drop_column('users', 'campus')
    op.drop_column('users', 'pan_number')
    op.drop_column('users', 'city')
    op.drop_column('users', 'emergency_email')
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'pincode')
    op.drop_column('users', 'emergency_phone')
    op.drop_column('users', 'salary')
    op.drop_column('users', 'country')
    op.drop_column('users', 'ifsc_code')
    op.drop_column('users', 'emergency_name')
    op.drop_column('users', 'position_id')
    op.drop_column('users', 'bank_name')
    op.drop_column('users', 'join_date')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'uan_number')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'state')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'reporting_manager_id')
    op.drop_column('users', 'exit_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exit_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reporting_manager_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('uan_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('join_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('position_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emergency_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ifsc_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emergency_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('employment_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='EmploymentType'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emergency_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pan_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('campus', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emergency_relation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('users_reporting_manager_id_fkey'), 'users', 'users', ['reporting_manager_id'], ['id'])
    op.create_foreign_key(op.f('users_position_id_fkey'), 'users', 'job_positions', ['position_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('system_settings', 'working_days',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('recruitment_jobs', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OPEN', 'CLOSED', 'PAUSED', 'FILLED', name='RecruitmentStatus'),
               existing_nullable=True)
    op.alter_column('recruitment_jobs', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='EmploymentType'),
               existing_nullable=True)
    op.drop_constraint(None, 'recruitment_applicants', type_='foreignkey')
    op.create_foreign_key(op.f('recruitment_applicants_job_id_fkey'), 'recruitment_applicants', 'recruitment_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recruitment_applicants', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFERED', 'HIRED', 'REJECTED', name='ApplicantStatus'),
               existing_nullable=True)
    op.drop_constraint('uq_goal_employee_cycle', 'performance_goals', type_='unique')
    op.create_unique_constraint(op.f('performance_goals_employee_id_cycle_id_key'), 'performance_goals', ['employee_id', 'cycle_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('performance_goals', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DRAFT', 'SUBMITTED', 'DIRECTOR_REVIEWED', 'FINALIZED', name='GoalStatus'),
               existing_nullable=True)
    op.add_column('onboarding_tasks', sa.Column('onboarding_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('onboarding_tasks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('onboarding_tasks', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='TaskPriority'), autoincrement=False, nullable=True))
    op.add_column('onboarding_tasks', sa.Column('assigned_to_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('onboarding_tasks', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('onboarding_tasks', sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='TaskStatus'), autoincrement=False, nullable=True))
    op.add_column('onboarding_tasks', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('onboarding_tasks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'onboarding_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('onboarding_tasks_assigned_to_id_fkey'), 'onboarding_tasks', 'users', ['assigned_to_id'], ['id'])
    op.create_foreign_key(op.f('onboarding_tasks_onboarding_id_fkey'), 'onboarding_tasks', 'onboarding_employees', ['onboarding_id'], ['id'], ondelete='CASCADE')
    op.drop_column('onboarding_tasks', 'is_completed')
    op.drop_column('onboarding_tasks', 'onboarding_record_id')
    op.alter_column('onboarding_employees', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='OnboardingStatus'),
               existing_nullable=True)
    op.add_column('offboarding_tasks', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('offboarding_tasks', sa.Column('offboarding_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('offboarding_tasks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('offboarding_tasks', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offboarding_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('offboarding_tasks_offboarding_id_fkey'), 'offboarding_tasks', 'offboarding_records', ['offboarding_id'], ['id'], ondelete='CASCADE')
    op.drop_column('offboarding_tasks', 'offboarding_record_id')
    op.add_column('offboarding_records', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('offboarding_records', sa.Column('resignation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('offboarding_records', sa.Column('forwarding_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('offboarding_records', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('offboarding_records', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('offboarding_records', sa.Column('personal_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('offboarding_records', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='OffboardingStatus'),
               nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_PENDING', 'ATTENDANCE_FLAGGED', 'ANNOUNCEMENT', 'ONBOARDING', 'PAYSLIP', 'SYSTEM', name='NotificationType'),
               existing_nullable=True)
    op.alter_column('holidays', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('NATIONAL', 'REGIONAL', 'UNIVERSITY', name='HolidayType'),
               existing_nullable=True)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.add_column('audit_logs', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint('uq_attendance_employee_date', 'attendance', type_='unique')
    op.create_unique_constraint(op.f('attendance_employee_id_date_key'), 'attendance', ['employee_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PRESENT', 'ABSENT', 'HALF_DAY', 'HOLIDAY', 'WEEKEND', 'ON_LEAVE', name='AttendanceStatus'),
               existing_nullable=True)
    op.add_column('appraisal_cycles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('appraisal_cycles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('appraisal_cycles', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ACTIVE', 'CLOSED', name='CycleStatus'),
               nullable=True)
    op.alter_column('announcements', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('NORMAL', 'IMPORTANT', 'URGENT', name='AnnouncementPriority'),
               existing_nullable=True)
    op.drop_constraint(None, 'announcement_reads', type_='foreignkey')
    op.create_foreign_key(op.f('announcement_reads_announcement_id_fkey'), 'announcement_reads', 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('announcement_reads_announcement_id_user_id_key'), 'announcement_reads', ['announcement_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('user_employments')
    op.drop_table('chat_messages')
    op.drop_table('user_financials')
    op.drop_table('user_emergency_contacts')
    op.drop_table('user_addresses')
    op.drop_table('chat_sessions')
    op.drop_table('roles')
    op.drop_table('postal_codes')
    op.drop_table('leave_policies')
    op.drop_table('bank_branches')
    # ### end Alembic commands ###
