"""Settings and early clockout

Revision ID: d97c07828246
Revises: fc7b41f5d4ff
Create Date: 2026-06-26 17:59:51.297765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97c07828246'
down_revision: Union[str, Sequence[str], None] = 'fc7b41f5d4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offboarding_tasks', 'offboarding_record_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('onboarding_tasks', 'onboarding_record_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('onboarding_tasks', 'assigned_to',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'EMPLOYEE'::character varying"))
    op.alter_column('onboarding_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('onboarding_tasks', 'assigned_to',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'EMPLOYEE'::character varying"))
    op.alter_column('onboarding_tasks', 'onboarding_record_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('offboarding_tasks', 'offboarding_record_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
