"""Initial Schema

Revision ID: f8f03a464327
Revises: 
Create Date: 2026-04-17 06:36:24.443079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f03a464327'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('default_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', 'leave_type', name='uq_policy_role_leavetype')
    )
    op.create_table('onboarding_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('is_auto_clocked_out', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_employee_date')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('pending_confirmation', sa.Text(), nullable=True),
    sa.Column('llm_used', sa.String(length=30), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.CheckConstraint('total_days >= 0', name='ck_total_days_non_negative'),
    sa.CheckConstraint('used_days >= 0', name='ck_used_days_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type', name='uq_balance_employee_leavetype')
    )
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_hod_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_hr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_hod_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_by_hr_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offboarding_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('last_working_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('clearance_status', sa.String(length=20), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_offboarding_employee')
    )
    op.create_table('onboarding_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_onboarding_employee')
    )
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=False),
    sa.Column('days_absent', sa.Integer(), nullable=False),
    sa.Column('days_on_leave', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('da', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('absent_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'month', 'year', name='uq_payslip_employee_month_year')
    )
    op.create_table('performance_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('goals_text', sa.Text(), nullable=False),
    sa.Column('self_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('self_comments', sa.Text(), nullable=True),
    sa.Column('hod_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('hod_comments', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('hr_comments', sa.Text(), nullable=True),
    sa.Column('finalized_by_id', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'cycle_id', name='uq_goal_employee_cycle')
    )
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('da', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('working_days_per_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_salary_employee')
    )
    op.create_table('offboarding_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offboarding_record_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offboarding_record_id'], ['offboarding_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('onboarding_record_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_record_id'], ['onboarding_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_tasks')
    op.drop_table('offboarding_tasks')
    op.drop_table('salary_structures')
    op.drop_table('performance_goals')
    op.drop_table('payslips')
    op.drop_table('onboarding_records')
    op.drop_table('offboarding_records')
    op.drop_table('leaves')
    op.drop_table('leave_balances')
    op.drop_table('chat_messages')
    op.drop_table('attendance')
    op.drop_table('employees')
    op.drop_table('chat_sessions')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('onboarding_templates')
    op.drop_table('leave_policies')
    op.drop_table('departments')
    op.drop_table('appraisal_cycles')
    # ### end Alembic commands ###
