"""Add ai_confidence to offboarding

Revision ID: fc7b41f5d4ff
Revises: 15e70bffbaa3
Create Date: 2026-06-19 08:39:51.946679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7b41f5d4ff'
down_revision: Union[str, Sequence[str], None] = '15e70bffbaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offboarding_records', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offboarding_records', 'ai_confidence')
    # ### end Alembic commands ###
