from __future__ import annotations
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.db.models.employee import Employee


class SalaryStructure(Base):
    """
    Defines the fixed salary components for an employee.
    HR sets this once when employee joins; can update anytime.
    One row per employee.
    """
    __tablename__ = "salary_structures"
    __table_args__ = (
        UniqueConstraint("employee_id", name="uq_salary_employee"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    employee_id: Mapped[int] = mapped_column(ForeignKey("employees.id"), nullable=False)

    # Earnings
    basic_salary: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    hra: Mapped[float] = mapped_column(Numeric(12, 2), default=0)          # House Rent Allowance
    ta: Mapped[float] = mapped_column(Numeric(12, 2), default=0)           # Travel Allowance
    da: Mapped[float] = mapped_column(Numeric(12, 2), default=0)           # Dearness Allowance
    other_allowances: Mapped[float] = mapped_column(Numeric(12, 2), default=0)

    # Deductions (fixed monthly)
    pf_deduction: Mapped[float] = mapped_column(Numeric(12, 2), default=0)     # Provident Fund
    professional_tax: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    tds_rate: Mapped[float] = mapped_column(Numeric(5, 2), default=0)          # TDS % (e.g. 10.00 = 10%)

    # Working days in a standard month
    working_days_per_month: Mapped[int] = mapped_column(Integer, default=26, nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)

    employee: Mapped[Employee] = relationship("Employee", back_populates="salary_structure")


class Payslip(Base):
    """
    Monthly payslip for each employee.
    Generated by HR; auto-calculates based on attendance + salary structure.
    One row per (employee, month, year).
    """
    __tablename__ = "payslips"
    __table_args__ = (
        UniqueConstraint("employee_id", "month", "year", name="uq_payslip_employee_month_year"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    employee_id: Mapped[int] = mapped_column(ForeignKey("employees.id"), nullable=False)
    month: Mapped[int] = mapped_column(Integer, nullable=False)   # 1-12
    year: Mapped[int] = mapped_column(Integer, nullable=False)

    # Attendance snapshot
    working_days: Mapped[int] = mapped_column(Integer, nullable=False)    # standard days in month
    days_present: Mapped[int] = mapped_column(Integer, nullable=False)    # from attendance table
    days_absent: Mapped[int] = mapped_column(Integer, nullable=False)     # working_days - present
    days_on_leave: Mapped[int] = mapped_column(Integer, default=0)        # approved leaves

    # Earnings (prorated based on attendance)
    basic_salary: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    hra: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    ta: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    da: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    other_allowances: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    gross_salary: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)

    # Deductions
    absent_deduction: Mapped[float] = mapped_column(Numeric(12, 2), default=0)  # per-day deduction * absent days
    pf_deduction: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    professional_tax: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    tds_deduction: Mapped[float] = mapped_column(Numeric(12, 2), default=0)     # calculated from tds_rate
    total_deductions: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)

    # Final
    net_pay: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)

    status: Mapped[str] = mapped_column(String(20), default="draft", nullable=False)
    # status: "draft" | "finalized"

    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
    finalized_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    employee: Mapped[Employee] = relationship("Employee", back_populates="payslips")